version: 0.2

env:
  variables:
    SRC_CODE: ""

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - n 16.13.2
  build:
    commands:
      - echo build phase
      - echo "node version:" node -v
      - echo "npm version:" npm -v
#      - npm install path
      - npm install 
      - npm run build
      - npm install -g aws-cdk
      - cdk deploy InvoiceApiServiceCdkStack

  post_build:
    commands:
      - echo post-build phase
      - echo Build completed on `date`
      - ls -al
#      - echo Artifacts copied to S3
